# Generated by Django 2.2.12 on 2020-05-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.TextField()),
                ('author', models.TextField()),
                ('isFile', models.BooleanField()),
                ('name', models.CharField(max_length=256)),
                ('path', models.TextField()),
                ('s3Link', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('deletedDate', models.DateField(default=None)),
            ],
        ),
    ]
