# Generated by Django 2.2.12 on 2020-05-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFile', models.BooleanField()),
                ('fid', models.IntegerField()),
                ('author', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('path', models.TextField()),
                ('s3Link', models.TextField(null=True)),
                ('fileSize', models.IntegerField()),
                ('createdDate', models.CharField(max_length=20)),
                ('deletedDate', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
