# Generated by Django 2.2.12 on 2020-06-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='createdDate',
        ),
    ]
